### ISSUE TITLE
运行错误问题

### ISSUE THREAD

**Issue by river0Love** [MeiHuaGuangShuo/idv-auto-player#1]
请问运行出现下列错误应如何解决
Traceback (most recent call last):
  File "E:\iGame\gua\idv-auto-player-main\main.py", line 59, in <module>
    model = YOLO("./best.pt")
            ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\ultralytics\models\yolo\model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "C:\Program Files\Python312\Lib\site-packages\ultralytics\engine\model.py", line 145, in __init__
    self._load(model, task=task)
  File "C:\Program Files\Python312\Lib\site-packages\ultralytics\engine\model.py", line 297, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\ultralytics\nn\tasks.py", line 902, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\ultralytics\nn\tasks.py", line 829, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\ultralytics\utils\patches.py", line 86, in torch_load
    return _torch_load(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\torch\serialization.py", line 1072, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\torch\serialization.py", line 480, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: PytorchStreamReader failed reading zip archive: invalid header or archive is corrupted

**Comment by MeiHuaGuangShuo** [comment]
您好，我这里没有问题。现在更新了。如果您仍然遇到这个问题，可以留下您的邮箱给我，我会私发给您
